title: Berg Ginú
author: Berg Ginú
email: ginu.berg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portifólio e notas de projetos (#Maker, #Python e #KDD)
theme: jekyll-theme-tactile

# social links
twitter_username: bergginu # DO NOT include the @ character, or else the build will fail!
github_username:  bergginu # DO NOT include the @ character, or else the build will fail!

show_excerpts: false
